### ISSUE TITLE
Tags for newer versions

### ISSUE THREAD

**Issue by maxilint** [holochain-open-dev/profiles#36]
The tags that are available https://github.com/holochain-open-dev/profiles/tags show up to 0.0.152, but right now, the hdk has also 0.0.154. Not sure if this affects something.

**Comment by guillemcordoba** [comment]
Oh yeah, thanks :)

**Comment by maxilint** [comment]
Will the 0.0.154 be added soon? or is there a quick fix for now that I can do on my project? I am not sure if downgrading to 0.0.152 is an option forr me as I am using the electron template. https://github.com/lightningrodlabs/electron-holochain-template

**Comment by guillemcordoba** [comment]
Oh look at that, @zippy added the version for hdk v0.0.154 as a branch, here: https://github.com/holochain-open-dev/profiles/tree/for-hdk-v0.0.154
