### ISSUE TITLE
Repo contains the DNA?

### ISSUE THREAD

**Issue by zippy** [holochain-open-dev/profiles#4]
I don't think the repo should contain the compiled DNA and hApp as it makes the downloads huge. Shouldn't they be release artifacts?

**Comment by nphias** [comment]
with this in the cargo.toml file ..  i still get quite a heavy download ..  am I doing something wrong?
[dependencies]
hc_zome_profiles = {git = "https://github.com/holochain-open-dev/profiles", package = "hc_zome_profiles"}

**Comment by guillemcordoba** [comment]
@nphias nothing wrong no... Also notice that zippy was talking about when cloning the git repository, as oposed as just using the crate like you are. I don't think there is a way to make it lighter since it basically only depends on the hdk.
